"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __exportStar = (this && this.__exportStar) || function(m, exports) {
    for (var p in m) if (p !== "default" && !Object.prototype.hasOwnProperty.call(exports, p)) __createBinding(exports, m, p);
};
Object.defineProperty(exports, "__esModule", { value: true });
__exportStar(require("./amazon-warehousing-and-distribution-client"), exports);
__exportStar(require("./aplus-content-api-client"), exports);
__exportStar(require("./application-management-api-client"), exports);
__exportStar(require("./catalog-items-api-client"), exports);
__exportStar(require("./catalog-items-api-client-v20201201"), exports);
__exportStar(require("./catalog-items-api-client-v20220401"), exports);
__exportStar(require("./data-kiosk-api-client"), exports);
__exportStar(require("./easy-ship-client"), exports);
__exportStar(require("./fba-inbound-eligibility-api-client"), exports);
__exportStar(require("./fba-inventory-api-client"), exports);
__exportStar(require("./feeds-api-client"), exports);
__exportStar(require("./feeds-api-client-v20210630"), exports);
__exportStar(require("./finances-api-client"), exports);
__exportStar(require("./fulfillment-inbound-api-client"), exports);
__exportStar(require("./fulfillment-inbound-api-client-v20240320"), exports);
__exportStar(require("./fulfillment-outbound-api-client"), exports);
__exportStar(require("./listings-items-api-client"), exports);
__exportStar(require("./listings-items-api-client-v20210801"), exports);
__exportStar(require("./listings-restrictions-api-client"), exports);
__exportStar(require("./merchant-fulfillment-api-client"), exports);
__exportStar(require("./messaging-api-client"), exports);
__exportStar(require("./notifications-api-client"), exports);
__exportStar(require("./orders-api-client"), exports);
__exportStar(require("./product-fees-api-client"), exports);
__exportStar(require("./product-pricing-api-client"), exports);
__exportStar(require("./product-pricing-api-client-v20220501"), exports);
__exportStar(require("./product-type-definitions-api-client"), exports);
__exportStar(require("./replenishment-api-client"), exports);
__exportStar(require("./reports-api-client"), exports);
__exportStar(require("./reports-api-client-v20210630"), exports);
__exportStar(require("./sales-api-client"), exports);
__exportStar(require("./sellers-api-client"), exports);
__exportStar(require("./services-api-client"), exports);
__exportStar(require("./shipment-invoicing-api-client"), exports);
__exportStar(require("./shipping-api-client"), exports);
__exportStar(require("./shipping-api-client-v2"), exports);
__exportStar(require("./solicitations-api-client"), exports);
__exportStar(require("./supply-sources-api-client"), exports);
__exportStar(require("./tokens-api-client"), exports);
__exportStar(require("./uploads-api-client"), exports);
__exportStar(require("./vendor-direct-fulfillment-inventory-api-client"), exports);
__exportStar(require("./vendor-direct-fulfillment-orders-api-client"), exports);
__exportStar(require("./vendor-direct-fulfillment-orders-api-client-v20211228"), exports);
__exportStar(require("./vendor-direct-fulfillment-payments-api-client"), exports);
__exportStar(require("./vendor-direct-fulfillment-sandbox-test-data-api-client"), exports);
__exportStar(require("./vendor-direct-fulfillment-shipping-api-client"), exports);
__exportStar(require("./vendor-direct-fulfillment-shipping-api-client-v20211228"), exports);
__exportStar(require("./vendor-direct-fulfillment-transactions-api-client"), exports);
__exportStar(require("./vendor-direct-fulfillment-transactions-api-client-v20211228"), exports);
__exportStar(require("./vendor-invoices-api-client"), exports);
__exportStar(require("./vendor-orders-api-client"), exports);
__exportStar(require("./vendor-shipments-api-client"), exports);
__exportStar(require("./vendor-transaction-status-api-client"), exports);
//# sourceMappingURL=index.js.map