/**
 * Selling Partner API for Messaging
 * With the Messaging API you can build applications that send messages to buyers. You can get a list of message types that are available for an order that you specify, then call an operation that sends a message to the buyer for that order. The Messaging API returns responses that are formed according to the <a href=https://tools.ietf.org/html/draft-kelly-json-hal-08>JSON Hypertext Application Language</a> (HAL) standard.
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Configuration } from './configuration';
import { AxiosPromise, AxiosInstance } from 'axios';
import { RequestArgs, BaseAPI } from './base';
/**
 * Represents a file uploaded to a destination that was created by the [createUploadDestinationForResource](doc:uploads-api-reference#post-uploads2020-11-01uploaddestinationsresource) operation of the Selling Partner API for Uploads.
 * @export
 * @interface Attachment
 */
export interface Attachment {
    /**
     * The identifier of the upload destination. Get this value by calling the [createUploadDestinationForResource](doc:uploads-api-reference#post-uploads2020-11-01uploaddestinationsresource) operation of the Uploads API.
     * @type {string}
     * @memberof Attachment
     */
    uploadDestinationId: string;
    /**
     * The name of the file, including the extension. This is the file name that will appear in the message. This does not need to match the file name of the file that you uploaded.
     * @type {string}
     * @memberof Attachment
     */
    fileName: string;
}
/**
 * The request schema for the createAmazonMotors operation.
 * @export
 * @interface CreateAmazonMotorsRequest
 */
export interface CreateAmazonMotorsRequest {
    /**
     * Attachments to include in the message to the buyer. If any text is included in the attachment, the text must be written in the buyer\'s language of preference, which can be retrieved from the GetAttributes operation.
     * @type {Array<Attachment>}
     * @memberof CreateAmazonMotorsRequest
     */
    attachments?: Array<Attachment>;
}
/**
 * The response schema for the createAmazonMotors operation.
 * @export
 * @interface CreateAmazonMotorsResponse
 */
export interface CreateAmazonMotorsResponse {
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof CreateAmazonMotorsResponse
     */
    errors?: Array<Error>;
}
/**
 * The request schema for the confirmCustomizationDetails operation.
 * @export
 * @interface CreateConfirmCustomizationDetailsRequest
 */
export interface CreateConfirmCustomizationDetailsRequest {
    /**
     * The text to be sent to the buyer. Only links related to customization details are allowed. Do not include HTML or email addresses. The text must be written in the buyer\'s language of preference, which can be retrieved from the GetAttributes operation.
     * @type {string}
     * @memberof CreateConfirmCustomizationDetailsRequest
     */
    text?: string;
    /**
     * Attachments to include in the message to the buyer.
     * @type {Array<Attachment>}
     * @memberof CreateConfirmCustomizationDetailsRequest
     */
    attachments?: Array<Attachment>;
}
/**
 * The response schema for the confirmCustomizationDetails operation.
 * @export
 * @interface CreateConfirmCustomizationDetailsResponse
 */
export interface CreateConfirmCustomizationDetailsResponse {
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof CreateConfirmCustomizationDetailsResponse
     */
    errors?: Array<Error>;
}
/**
 * The request schema for the createConfirmDeliveryDetails operation.
 * @export
 * @interface CreateConfirmDeliveryDetailsRequest
 */
export interface CreateConfirmDeliveryDetailsRequest {
    /**
     * The text to be sent to the buyer. Only links related to order delivery are allowed. Do not include HTML or email addresses. The text must be written in the buyer\'s language of preference, which can be retrieved from the GetAttributes operation.
     * @type {string}
     * @memberof CreateConfirmDeliveryDetailsRequest
     */
    text?: string;
}
/**
 * The response schema for the createConfirmDeliveryDetails operation.
 * @export
 * @interface CreateConfirmDeliveryDetailsResponse
 */
export interface CreateConfirmDeliveryDetailsResponse {
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof CreateConfirmDeliveryDetailsResponse
     */
    errors?: Array<Error>;
}
/**
 * The request schema for the createConfirmOrderDetails operation.
 * @export
 * @interface CreateConfirmOrderDetailsRequest
 */
export interface CreateConfirmOrderDetailsRequest {
    /**
     * The text to be sent to the buyer. Only links related to order completion are allowed. Do not include HTML or email addresses. The text must be written in the buyer\'s language of preference, which can be retrieved from the GetAttributes operation.
     * @type {string}
     * @memberof CreateConfirmOrderDetailsRequest
     */
    text?: string;
}
/**
 * The response schema for the createConfirmOrderDetails operation.
 * @export
 * @interface CreateConfirmOrderDetailsResponse
 */
export interface CreateConfirmOrderDetailsResponse {
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof CreateConfirmOrderDetailsResponse
     */
    errors?: Array<Error>;
}
/**
 * The request schema for the createConfirmServiceDetails operation.
 * @export
 * @interface CreateConfirmServiceDetailsRequest
 */
export interface CreateConfirmServiceDetailsRequest {
    /**
     * The text to be sent to the buyer. Only links related to Home Service calls are allowed. Do not include HTML or email addresses. The text must be written in the buyer\'s language of preference, which can be retrieved from the GetAttributes operation.
     * @type {string}
     * @memberof CreateConfirmServiceDetailsRequest
     */
    text?: string;
}
/**
 * The response schema for the createConfirmServiceDetails operation.
 * @export
 * @interface CreateConfirmServiceDetailsResponse
 */
export interface CreateConfirmServiceDetailsResponse {
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof CreateConfirmServiceDetailsResponse
     */
    errors?: Array<Error>;
}
/**
 * The request schema for the createDigitalAccessKey operation.
 * @export
 * @interface CreateDigitalAccessKeyRequest
 */
export interface CreateDigitalAccessKeyRequest {
    /**
     * The text to be sent to the buyer. Only links related to the digital access key are allowed. Do not include HTML or email addresses. The text must be written in the buyer\'s language of preference, which can be retrieved from the GetAttributes operation.
     * @type {string}
     * @memberof CreateDigitalAccessKeyRequest
     */
    text?: string;
    /**
     * Attachments to include in the message to the buyer.
     * @type {Array<Attachment>}
     * @memberof CreateDigitalAccessKeyRequest
     */
    attachments?: Array<Attachment>;
}
/**
 * The response schema for the createDigitalAccessKey operation.
 * @export
 * @interface CreateDigitalAccessKeyResponse
 */
export interface CreateDigitalAccessKeyResponse {
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof CreateDigitalAccessKeyResponse
     */
    errors?: Array<Error>;
}
/**
 * The request schema for the createLegalDisclosure operation.
 * @export
 * @interface CreateLegalDisclosureRequest
 */
export interface CreateLegalDisclosureRequest {
    /**
     * Attachments to include in the message to the buyer. If any text is included in the attachment, the text must be written in the buyer\'s language of preference, which can be retrieved from the GetAttributes operation.
     * @type {Array<Attachment>}
     * @memberof CreateLegalDisclosureRequest
     */
    attachments?: Array<Attachment>;
}
/**
 * The response schema for the createLegalDisclosure operation.
 * @export
 * @interface CreateLegalDisclosureResponse
 */
export interface CreateLegalDisclosureResponse {
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof CreateLegalDisclosureResponse
     */
    errors?: Array<Error>;
}
/**
 * The response schema for the createNegativeFeedbackRemoval operation.
 * @export
 * @interface CreateNegativeFeedbackRemovalResponse
 */
export interface CreateNegativeFeedbackRemovalResponse {
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof CreateNegativeFeedbackRemovalResponse
     */
    errors?: Array<Error>;
}
/**
 * The request schema for the createUnexpectedProblem operation.
 * @export
 * @interface CreateUnexpectedProblemRequest
 */
export interface CreateUnexpectedProblemRequest {
    /**
     * The text to be sent to the buyer. Only links related to unexpected problem calls are allowed. Do not include HTML or email addresses. The text must be written in the buyer\'s language of preference, which can be retrieved from the GetAttributes operation.
     * @type {string}
     * @memberof CreateUnexpectedProblemRequest
     */
    text?: string;
}
/**
 * The response schema for the createUnexpectedProblem operation.
 * @export
 * @interface CreateUnexpectedProblemResponse
 */
export interface CreateUnexpectedProblemResponse {
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof CreateUnexpectedProblemResponse
     */
    errors?: Array<Error>;
}
/**
 * The request schema for the createWarranty operation.
 * @export
 * @interface CreateWarrantyRequest
 */
export interface CreateWarrantyRequest {
    /**
     * Attachments to include in the message to the buyer. If any text is included in the attachment, the text must be written in the buyer\'s language of preference, which can be retrieved from the GetAttributes operation.
     * @type {Array<Attachment>}
     * @memberof CreateWarrantyRequest
     */
    attachments?: Array<Attachment>;
    /**
     * The start date of the warranty coverage to include in the message to the buyer.
     * @type {string}
     * @memberof CreateWarrantyRequest
     */
    coverageStartDate?: string;
    /**
     * The end date of the warranty coverage to include in the message to the buyer.
     * @type {string}
     * @memberof CreateWarrantyRequest
     */
    coverageEndDate?: string;
}
/**
 * The response schema for the createWarranty operation.
 * @export
 * @interface CreateWarrantyResponse
 */
export interface CreateWarrantyResponse {
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof CreateWarrantyResponse
     */
    errors?: Array<Error>;
}
/**
 * The response schema for the GetAttributes operation.
 * @export
 * @interface GetAttributesResponse
 */
export interface GetAttributesResponse {
    /**
     *
     * @type {GetAttributesResponseBuyer}
     * @memberof GetAttributesResponse
     */
    buyer?: GetAttributesResponseBuyer;
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof GetAttributesResponse
     */
    errors?: Array<Error>;
}
/**
 * The list of attributes related to the buyer.
 * @export
 * @interface GetAttributesResponseBuyer
 */
export interface GetAttributesResponseBuyer {
    /**
     * The buyer\'s language of preference, indicated with a locale-specific language tag. Examples: \"en-US\", \"zh-CN\", and \"en-GB\".
     * @type {string}
     * @memberof GetAttributesResponseBuyer
     */
    locale?: string;
}
/**
 * Describes a messaging action that can be taken for an order. Provides a JSON Hypertext Application Language (HAL) link to the JSON schema document that describes the expected input.
 * @export
 * @interface GetMessagingActionResponse
 */
export interface GetMessagingActionResponse {
    /**
     *
     * @type {GetMessagingActionResponseLinks}
     * @memberof GetMessagingActionResponse
     */
    _links?: GetMessagingActionResponseLinks;
    /**
     *
     * @type {GetMessagingActionResponseEmbedded}
     * @memberof GetMessagingActionResponse
     */
    _embedded?: GetMessagingActionResponseEmbedded;
    /**
     *
     * @type {MessagingAction}
     * @memberof GetMessagingActionResponse
     */
    payload?: MessagingAction;
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof GetMessagingActionResponse
     */
    errors?: Array<Error>;
}
/**
 *
 * @export
 * @interface GetMessagingActionResponseEmbedded
 */
export interface GetMessagingActionResponseEmbedded {
    /**
     *
     * @type {GetSchemaResponse}
     * @memberof GetMessagingActionResponseEmbedded
     */
    schema?: GetSchemaResponse;
}
/**
 *
 * @export
 * @interface GetMessagingActionResponseLinks
 */
export interface GetMessagingActionResponseLinks {
    /**
     *
     * @type {LinkObject}
     * @memberof GetMessagingActionResponseLinks
     */
    self: LinkObject;
    /**
     *
     * @type {LinkObject}
     * @memberof GetMessagingActionResponseLinks
     */
    schema: LinkObject;
}
/**
 * The response schema for the getMessagingActionsForOrder operation.
 * @export
 * @interface GetMessagingActionsForOrderResponse
 */
export interface GetMessagingActionsForOrderResponse {
    /**
     *
     * @type {GetMessagingActionsForOrderResponseLinks}
     * @memberof GetMessagingActionsForOrderResponse
     */
    _links?: GetMessagingActionsForOrderResponseLinks;
    /**
     *
     * @type {GetMessagingActionsForOrderResponseEmbedded}
     * @memberof GetMessagingActionsForOrderResponse
     */
    _embedded?: GetMessagingActionsForOrderResponseEmbedded;
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof GetMessagingActionsForOrderResponse
     */
    errors?: Array<Error>;
}
/**
 *
 * @export
 * @interface GetMessagingActionsForOrderResponseEmbedded
 */
export interface GetMessagingActionsForOrderResponseEmbedded {
    /**
     *
     * @type {Array<GetMessagingActionResponse>}
     * @memberof GetMessagingActionsForOrderResponseEmbedded
     */
    actions: Array<GetMessagingActionResponse>;
}
/**
 *
 * @export
 * @interface GetMessagingActionsForOrderResponseLinks
 */
export interface GetMessagingActionsForOrderResponseLinks {
    /**
     *
     * @type {LinkObject}
     * @memberof GetMessagingActionsForOrderResponseLinks
     */
    self: LinkObject;
    /**
     * Eligible actions for the specified amazonOrderId.
     * @type {Array<LinkObject>}
     * @memberof GetMessagingActionsForOrderResponseLinks
     */
    actions: Array<LinkObject>;
}
/**
 *
 * @export
 * @interface GetSchemaResponse
 */
export interface GetSchemaResponse {
    /**
     *
     * @type {GetSchemaResponseLinks}
     * @memberof GetSchemaResponse
     */
    _links?: GetSchemaResponseLinks;
    /**
     * A JSON schema document describing the expected payload of the action. This object can be validated against <a href=http://json-schema.org/draft-04/schema>http://json-schema.org/draft-04/schema</a>.
     * @type {{ [key: string]: object; }}
     * @memberof GetSchemaResponse
     */
    payload?: {
        [key: string]: object;
    };
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof GetSchemaResponse
     */
    errors?: Array<Error>;
}
/**
 *
 * @export
 * @interface GetSchemaResponseLinks
 */
export interface GetSchemaResponseLinks {
    /**
     *
     * @type {LinkObject}
     * @memberof GetSchemaResponseLinks
     */
    self: LinkObject;
}
/**
 * The request schema for the sendInvoice operation.
 * @export
 * @interface InvoiceRequest
 */
export interface InvoiceRequest {
    /**
     * Attachments to include in the message to the buyer.
     * @type {Array<Attachment>}
     * @memberof InvoiceRequest
     */
    attachments?: Array<Attachment>;
}
/**
 * The response schema for the sendInvoice operation.
 * @export
 * @interface InvoiceResponse
 */
export interface InvoiceResponse {
    /**
     * A list of error responses returned when a request is unsuccessful.
     * @type {Array<Error>}
     * @memberof InvoiceResponse
     */
    errors?: Array<Error>;
}
/**
 * A Link object.
 * @export
 * @interface LinkObject
 */
export interface LinkObject {
    /**
     * A URI for this object.
     * @type {string}
     * @memberof LinkObject
     */
    href: string;
    /**
     * An identifier for this object.
     * @type {string}
     * @memberof LinkObject
     */
    name?: string;
}
/**
 * A simple object containing the name of the template.
 * @export
 * @interface MessagingAction
 */
export interface MessagingAction {
    /**
     *
     * @type {string}
     * @memberof MessagingAction
     */
    name: string;
}
/**
 * Error response returned when the request is unsuccessful.
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * An error code that identifies the type of error that occurred.
     * @type {string}
     * @memberof ModelError
     */
    code: string;
    /**
     * A message that describes the error condition.
     * @type {string}
     * @memberof ModelError
     */
    message: string;
    /**
     * Additional details that can help the caller understand or fix the issue.
     * @type {string}
     * @memberof ModelError
     */
    details?: string;
}
/**
 * MessagingApi - axios parameter creator
 * @export
 */
export declare const MessagingApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     * Sends a message asking a buyer to provide or verify customization details such as name spelling, images, initials, etc.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmCustomizationDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    confirmCustomizationDetails: (amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmCustomizationDetailsRequest, options?: any) => Promise<RequestArgs>;
    /**
     * Sends a message to a buyer to provide details about an Amazon Motors order. This message can only be sent by Amazon Motors sellers.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateAmazonMotorsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createAmazonMotors: (amazonOrderId: string, marketplaceIds: Array<string>, body: CreateAmazonMotorsRequest, options?: any) => Promise<RequestArgs>;
    /**
     * Sends a message to a buyer to arrange a delivery or to confirm contact information for making a delivery.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmDeliveryDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConfirmDeliveryDetails: (amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmDeliveryDetailsRequest, options?: any) => Promise<RequestArgs>;
    /**
     * Sends a message to ask a buyer an order-related question prior to shipping their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmOrderDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConfirmOrderDetails: (amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmOrderDetailsRequest, options?: any) => Promise<RequestArgs>;
    /**
     * Sends a message to contact a Home Service customer to arrange a service call or to gather information prior to a service call.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmServiceDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConfirmServiceDetails: (amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmServiceDetailsRequest, options?: any) => Promise<RequestArgs>;
    /**
     * Sends a message to a buyer to share a digital access key needed to utilize digital content in their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateDigitalAccessKeyRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createDigitalAccessKey: (amazonOrderId: string, marketplaceIds: Array<string>, body: CreateDigitalAccessKeyRequest, options?: any) => Promise<RequestArgs>;
    /**
     * Sends a critical message that contains documents that a seller is legally obligated to provide to the buyer. This message should only be used to deliver documents that are required by law.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateLegalDisclosureRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createLegalDisclosure: (amazonOrderId: string, marketplaceIds: Array<string>, body: CreateLegalDisclosureRequest, options?: any) => Promise<RequestArgs>;
    /**
     * Sends a non-critical message that asks a buyer to remove their negative feedback. This message should only be sent after the seller has resolved the buyer\'s problem.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNegativeFeedbackRemoval: (amazonOrderId: string, marketplaceIds: Array<string>, options?: any) => Promise<RequestArgs>;
    /**
     * Sends a critical message to a buyer that an unexpected problem was encountered affecting the completion of the order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateUnexpectedProblemRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createUnexpectedProblem: (amazonOrderId: string, marketplaceIds: Array<string>, body: CreateUnexpectedProblemRequest, options?: any) => Promise<RequestArgs>;
    /**
     * Sends a message to a buyer to provide details about warranty information on a purchase in their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateWarrantyRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createWarranty: (amazonOrderId: string, marketplaceIds: Array<string>, body: CreateWarrantyRequest, options?: any) => Promise<RequestArgs>;
    /**
     * Returns a response containing attributes related to an order. This includes buyer preferences.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAttributes: (amazonOrderId: string, marketplaceIds: Array<string>, options?: any) => Promise<RequestArgs>;
    /**
     * Returns a list of message types that are available for an order that you specify. A message type is represented by an actions object, which contains a path and query parameter(s). You can use the path and parameter(s) to call an operation that sends a message.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which you want a list of available message types.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMessagingActionsForOrder: (amazonOrderId: string, marketplaceIds: Array<string>, options?: any) => Promise<RequestArgs>;
    /**
     * Sends a message providing the buyer an invoice
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {InvoiceRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendInvoice: (amazonOrderId: string, marketplaceIds: Array<string>, body: InvoiceRequest, options?: any) => Promise<RequestArgs>;
};
/**
 * MessagingApi - functional programming interface
 * @export
 */
export declare const MessagingApiFp: (configuration?: Configuration) => {
    /**
     * Sends a message asking a buyer to provide or verify customization details such as name spelling, images, initials, etc.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmCustomizationDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    confirmCustomizationDetails(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmCustomizationDetailsRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateConfirmCustomizationDetailsResponse>>;
    /**
     * Sends a message to a buyer to provide details about an Amazon Motors order. This message can only be sent by Amazon Motors sellers.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateAmazonMotorsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createAmazonMotors(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateAmazonMotorsRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateAmazonMotorsResponse>>;
    /**
     * Sends a message to a buyer to arrange a delivery or to confirm contact information for making a delivery.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmDeliveryDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConfirmDeliveryDetails(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmDeliveryDetailsRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateConfirmDeliveryDetailsResponse>>;
    /**
     * Sends a message to ask a buyer an order-related question prior to shipping their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmOrderDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConfirmOrderDetails(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmOrderDetailsRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateConfirmOrderDetailsResponse>>;
    /**
     * Sends a message to contact a Home Service customer to arrange a service call or to gather information prior to a service call.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmServiceDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConfirmServiceDetails(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmServiceDetailsRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateConfirmServiceDetailsResponse>>;
    /**
     * Sends a message to a buyer to share a digital access key needed to utilize digital content in their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateDigitalAccessKeyRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createDigitalAccessKey(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateDigitalAccessKeyRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDigitalAccessKeyResponse>>;
    /**
     * Sends a critical message that contains documents that a seller is legally obligated to provide to the buyer. This message should only be used to deliver documents that are required by law.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateLegalDisclosureRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createLegalDisclosure(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateLegalDisclosureRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateLegalDisclosureResponse>>;
    /**
     * Sends a non-critical message that asks a buyer to remove their negative feedback. This message should only be sent after the seller has resolved the buyer\'s problem.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNegativeFeedbackRemoval(amazonOrderId: string, marketplaceIds: Array<string>, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateNegativeFeedbackRemovalResponse>>;
    /**
     * Sends a critical message to a buyer that an unexpected problem was encountered affecting the completion of the order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateUnexpectedProblemRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createUnexpectedProblem(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateUnexpectedProblemRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateUnexpectedProblemResponse>>;
    /**
     * Sends a message to a buyer to provide details about warranty information on a purchase in their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateWarrantyRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createWarranty(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateWarrantyRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateWarrantyResponse>>;
    /**
     * Returns a response containing attributes related to an order. This includes buyer preferences.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAttributes(amazonOrderId: string, marketplaceIds: Array<string>, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAttributesResponse>>;
    /**
     * Returns a list of message types that are available for an order that you specify. A message type is represented by an actions object, which contains a path and query parameter(s). You can use the path and parameter(s) to call an operation that sends a message.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which you want a list of available message types.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMessagingActionsForOrder(amazonOrderId: string, marketplaceIds: Array<string>, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetMessagingActionsForOrderResponse>>;
    /**
     * Sends a message providing the buyer an invoice
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {InvoiceRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendInvoice(amazonOrderId: string, marketplaceIds: Array<string>, body: InvoiceRequest, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InvoiceResponse>>;
};
/**
 * MessagingApi - factory interface
 * @export
 */
export declare const MessagingApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     * Sends a message asking a buyer to provide or verify customization details such as name spelling, images, initials, etc.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmCustomizationDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    confirmCustomizationDetails(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmCustomizationDetailsRequest, options?: any): AxiosPromise<CreateConfirmCustomizationDetailsResponse>;
    /**
     * Sends a message to a buyer to provide details about an Amazon Motors order. This message can only be sent by Amazon Motors sellers.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateAmazonMotorsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createAmazonMotors(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateAmazonMotorsRequest, options?: any): AxiosPromise<CreateAmazonMotorsResponse>;
    /**
     * Sends a message to a buyer to arrange a delivery or to confirm contact information for making a delivery.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmDeliveryDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConfirmDeliveryDetails(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmDeliveryDetailsRequest, options?: any): AxiosPromise<CreateConfirmDeliveryDetailsResponse>;
    /**
     * Sends a message to ask a buyer an order-related question prior to shipping their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmOrderDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConfirmOrderDetails(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmOrderDetailsRequest, options?: any): AxiosPromise<CreateConfirmOrderDetailsResponse>;
    /**
     * Sends a message to contact a Home Service customer to arrange a service call or to gather information prior to a service call.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateConfirmServiceDetailsRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createConfirmServiceDetails(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateConfirmServiceDetailsRequest, options?: any): AxiosPromise<CreateConfirmServiceDetailsResponse>;
    /**
     * Sends a message to a buyer to share a digital access key needed to utilize digital content in their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateDigitalAccessKeyRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createDigitalAccessKey(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateDigitalAccessKeyRequest, options?: any): AxiosPromise<CreateDigitalAccessKeyResponse>;
    /**
     * Sends a critical message that contains documents that a seller is legally obligated to provide to the buyer. This message should only be used to deliver documents that are required by law.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateLegalDisclosureRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createLegalDisclosure(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateLegalDisclosureRequest, options?: any): AxiosPromise<CreateLegalDisclosureResponse>;
    /**
     * Sends a non-critical message that asks a buyer to remove their negative feedback. This message should only be sent after the seller has resolved the buyer\'s problem.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNegativeFeedbackRemoval(amazonOrderId: string, marketplaceIds: Array<string>, options?: any): AxiosPromise<CreateNegativeFeedbackRemovalResponse>;
    /**
     * Sends a critical message to a buyer that an unexpected problem was encountered affecting the completion of the order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateUnexpectedProblemRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createUnexpectedProblem(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateUnexpectedProblemRequest, options?: any): AxiosPromise<CreateUnexpectedProblemResponse>;
    /**
     * Sends a message to a buyer to provide details about warranty information on a purchase in their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {CreateWarrantyRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createWarranty(amazonOrderId: string, marketplaceIds: Array<string>, body: CreateWarrantyRequest, options?: any): AxiosPromise<CreateWarrantyResponse>;
    /**
     * Returns a response containing attributes related to an order. This includes buyer preferences.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAttributes(amazonOrderId: string, marketplaceIds: Array<string>, options?: any): AxiosPromise<GetAttributesResponse>;
    /**
     * Returns a list of message types that are available for an order that you specify. A message type is represented by an actions object, which contains a path and query parameter(s). You can use the path and parameter(s) to call an operation that sends a message.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which you want a list of available message types.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getMessagingActionsForOrder(amazonOrderId: string, marketplaceIds: Array<string>, options?: any): AxiosPromise<GetMessagingActionsForOrderResponse>;
    /**
     * Sends a message providing the buyer an invoice
     * @param {string} amazonOrderId An Amazon order identifier. This specifies the order for which a message is sent.
     * @param {Array<string>} marketplaceIds A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @param {InvoiceRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    sendInvoice(amazonOrderId: string, marketplaceIds: Array<string>, body: InvoiceRequest, options?: any): AxiosPromise<InvoiceResponse>;
};
/**
 * Request parameters for confirmCustomizationDetails operation in MessagingApi.
 * @export
 * @interface MessagingApiConfirmCustomizationDetailsRequest
 */
export interface MessagingApiConfirmCustomizationDetailsRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiConfirmCustomizationDetails
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiConfirmCustomizationDetails
     */
    readonly marketplaceIds: Array<string>;
    /**
     *
     * @type {CreateConfirmCustomizationDetailsRequest}
     * @memberof MessagingApiConfirmCustomizationDetails
     */
    readonly body: CreateConfirmCustomizationDetailsRequest;
}
/**
 * Request parameters for createAmazonMotors operation in MessagingApi.
 * @export
 * @interface MessagingApiCreateAmazonMotorsRequest
 */
export interface MessagingApiCreateAmazonMotorsRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiCreateAmazonMotors
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiCreateAmazonMotors
     */
    readonly marketplaceIds: Array<string>;
    /**
     *
     * @type {CreateAmazonMotorsRequest}
     * @memberof MessagingApiCreateAmazonMotors
     */
    readonly body: CreateAmazonMotorsRequest;
}
/**
 * Request parameters for createConfirmDeliveryDetails operation in MessagingApi.
 * @export
 * @interface MessagingApiCreateConfirmDeliveryDetailsRequest
 */
export interface MessagingApiCreateConfirmDeliveryDetailsRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiCreateConfirmDeliveryDetails
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiCreateConfirmDeliveryDetails
     */
    readonly marketplaceIds: Array<string>;
    /**
     *
     * @type {CreateConfirmDeliveryDetailsRequest}
     * @memberof MessagingApiCreateConfirmDeliveryDetails
     */
    readonly body: CreateConfirmDeliveryDetailsRequest;
}
/**
 * Request parameters for createConfirmOrderDetails operation in MessagingApi.
 * @export
 * @interface MessagingApiCreateConfirmOrderDetailsRequest
 */
export interface MessagingApiCreateConfirmOrderDetailsRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiCreateConfirmOrderDetails
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiCreateConfirmOrderDetails
     */
    readonly marketplaceIds: Array<string>;
    /**
     *
     * @type {CreateConfirmOrderDetailsRequest}
     * @memberof MessagingApiCreateConfirmOrderDetails
     */
    readonly body: CreateConfirmOrderDetailsRequest;
}
/**
 * Request parameters for createConfirmServiceDetails operation in MessagingApi.
 * @export
 * @interface MessagingApiCreateConfirmServiceDetailsRequest
 */
export interface MessagingApiCreateConfirmServiceDetailsRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiCreateConfirmServiceDetails
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiCreateConfirmServiceDetails
     */
    readonly marketplaceIds: Array<string>;
    /**
     *
     * @type {CreateConfirmServiceDetailsRequest}
     * @memberof MessagingApiCreateConfirmServiceDetails
     */
    readonly body: CreateConfirmServiceDetailsRequest;
}
/**
 * Request parameters for createDigitalAccessKey operation in MessagingApi.
 * @export
 * @interface MessagingApiCreateDigitalAccessKeyRequest
 */
export interface MessagingApiCreateDigitalAccessKeyRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiCreateDigitalAccessKey
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiCreateDigitalAccessKey
     */
    readonly marketplaceIds: Array<string>;
    /**
     *
     * @type {CreateDigitalAccessKeyRequest}
     * @memberof MessagingApiCreateDigitalAccessKey
     */
    readonly body: CreateDigitalAccessKeyRequest;
}
/**
 * Request parameters for createLegalDisclosure operation in MessagingApi.
 * @export
 * @interface MessagingApiCreateLegalDisclosureRequest
 */
export interface MessagingApiCreateLegalDisclosureRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiCreateLegalDisclosure
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiCreateLegalDisclosure
     */
    readonly marketplaceIds: Array<string>;
    /**
     *
     * @type {CreateLegalDisclosureRequest}
     * @memberof MessagingApiCreateLegalDisclosure
     */
    readonly body: CreateLegalDisclosureRequest;
}
/**
 * Request parameters for createNegativeFeedbackRemoval operation in MessagingApi.
 * @export
 * @interface MessagingApiCreateNegativeFeedbackRemovalRequest
 */
export interface MessagingApiCreateNegativeFeedbackRemovalRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiCreateNegativeFeedbackRemoval
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiCreateNegativeFeedbackRemoval
     */
    readonly marketplaceIds: Array<string>;
}
/**
 * Request parameters for createUnexpectedProblem operation in MessagingApi.
 * @export
 * @interface MessagingApiCreateUnexpectedProblemRequest
 */
export interface MessagingApiCreateUnexpectedProblemRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiCreateUnexpectedProblem
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiCreateUnexpectedProblem
     */
    readonly marketplaceIds: Array<string>;
    /**
     *
     * @type {CreateUnexpectedProblemRequest}
     * @memberof MessagingApiCreateUnexpectedProblem
     */
    readonly body: CreateUnexpectedProblemRequest;
}
/**
 * Request parameters for createWarranty operation in MessagingApi.
 * @export
 * @interface MessagingApiCreateWarrantyRequest
 */
export interface MessagingApiCreateWarrantyRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiCreateWarranty
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiCreateWarranty
     */
    readonly marketplaceIds: Array<string>;
    /**
     *
     * @type {CreateWarrantyRequest}
     * @memberof MessagingApiCreateWarranty
     */
    readonly body: CreateWarrantyRequest;
}
/**
 * Request parameters for getAttributes operation in MessagingApi.
 * @export
 * @interface MessagingApiGetAttributesRequest
 */
export interface MessagingApiGetAttributesRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiGetAttributes
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiGetAttributes
     */
    readonly marketplaceIds: Array<string>;
}
/**
 * Request parameters for getMessagingActionsForOrder operation in MessagingApi.
 * @export
 * @interface MessagingApiGetMessagingActionsForOrderRequest
 */
export interface MessagingApiGetMessagingActionsForOrderRequest {
    /**
     * An Amazon order identifier. This specifies the order for which you want a list of available message types.
     * @type {string}
     * @memberof MessagingApiGetMessagingActionsForOrder
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiGetMessagingActionsForOrder
     */
    readonly marketplaceIds: Array<string>;
}
/**
 * Request parameters for sendInvoice operation in MessagingApi.
 * @export
 * @interface MessagingApiSendInvoiceRequest
 */
export interface MessagingApiSendInvoiceRequest {
    /**
     * An Amazon order identifier. This specifies the order for which a message is sent.
     * @type {string}
     * @memberof MessagingApiSendInvoice
     */
    readonly amazonOrderId: string;
    /**
     * A marketplace identifier. This specifies the marketplace in which the order was placed. Only one marketplace can be specified.
     * @type {Array<string>}
     * @memberof MessagingApiSendInvoice
     */
    readonly marketplaceIds: Array<string>;
    /**
     *
     * @type {InvoiceRequest}
     * @memberof MessagingApiSendInvoice
     */
    readonly body: InvoiceRequest;
}
/**
 * MessagingApi - object-oriented interface
 * @export
 * @class MessagingApi
 * @extends {BaseAPI}
 */
export declare class MessagingApi extends BaseAPI {
    /**
     * Sends a message asking a buyer to provide or verify customization details such as name spelling, images, initials, etc.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {MessagingApiConfirmCustomizationDetailsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    confirmCustomizationDetails(requestParameters: MessagingApiConfirmCustomizationDetailsRequest, options?: any): Promise<import("axios").AxiosResponse<CreateConfirmCustomizationDetailsResponse, any>>;
    /**
     * Sends a message to a buyer to provide details about an Amazon Motors order. This message can only be sent by Amazon Motors sellers.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {MessagingApiCreateAmazonMotorsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    createAmazonMotors(requestParameters: MessagingApiCreateAmazonMotorsRequest, options?: any): Promise<import("axios").AxiosResponse<CreateAmazonMotorsResponse, any>>;
    /**
     * Sends a message to a buyer to arrange a delivery or to confirm contact information for making a delivery.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {MessagingApiCreateConfirmDeliveryDetailsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    createConfirmDeliveryDetails(requestParameters: MessagingApiCreateConfirmDeliveryDetailsRequest, options?: any): Promise<import("axios").AxiosResponse<CreateConfirmDeliveryDetailsResponse, any>>;
    /**
     * Sends a message to ask a buyer an order-related question prior to shipping their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {MessagingApiCreateConfirmOrderDetailsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    createConfirmOrderDetails(requestParameters: MessagingApiCreateConfirmOrderDetailsRequest, options?: any): Promise<import("axios").AxiosResponse<CreateConfirmOrderDetailsResponse, any>>;
    /**
     * Sends a message to contact a Home Service customer to arrange a service call or to gather information prior to a service call.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {MessagingApiCreateConfirmServiceDetailsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    createConfirmServiceDetails(requestParameters: MessagingApiCreateConfirmServiceDetailsRequest, options?: any): Promise<import("axios").AxiosResponse<CreateConfirmServiceDetailsResponse, any>>;
    /**
     * Sends a message to a buyer to share a digital access key needed to utilize digital content in their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {MessagingApiCreateDigitalAccessKeyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    createDigitalAccessKey(requestParameters: MessagingApiCreateDigitalAccessKeyRequest, options?: any): Promise<import("axios").AxiosResponse<CreateDigitalAccessKeyResponse, any>>;
    /**
     * Sends a critical message that contains documents that a seller is legally obligated to provide to the buyer. This message should only be used to deliver documents that are required by law.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {MessagingApiCreateLegalDisclosureRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    createLegalDisclosure(requestParameters: MessagingApiCreateLegalDisclosureRequest, options?: any): Promise<import("axios").AxiosResponse<CreateLegalDisclosureResponse, any>>;
    /**
     * Sends a non-critical message that asks a buyer to remove their negative feedback. This message should only be sent after the seller has resolved the buyer\'s problem.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {MessagingApiCreateNegativeFeedbackRemovalRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    createNegativeFeedbackRemoval(requestParameters: MessagingApiCreateNegativeFeedbackRemovalRequest, options?: any): Promise<import("axios").AxiosResponse<CreateNegativeFeedbackRemovalResponse, any>>;
    /**
     * Sends a critical message to a buyer that an unexpected problem was encountered affecting the completion of the order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {MessagingApiCreateUnexpectedProblemRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    createUnexpectedProblem(requestParameters: MessagingApiCreateUnexpectedProblemRequest, options?: any): Promise<import("axios").AxiosResponse<CreateUnexpectedProblemResponse, any>>;
    /**
     * Sends a message to a buyer to provide details about warranty information on a purchase in their order.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {MessagingApiCreateWarrantyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    createWarranty(requestParameters: MessagingApiCreateWarrantyRequest, options?: any): Promise<import("axios").AxiosResponse<CreateWarrantyResponse, any>>;
    /**
     * Returns a response containing attributes related to an order. This includes buyer preferences.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |
     * @param {MessagingApiGetAttributesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    getAttributes(requestParameters: MessagingApiGetAttributesRequest, options?: any): Promise<import("axios").AxiosResponse<GetAttributesResponse, any>>;
    /**
     * Returns a list of message types that are available for an order that you specify. A message type is represented by an actions object, which contains a path and query parameter(s). You can use the path and parameter(s) to call an operation that sends a message.  **Usage Plan:**  | Rate (requests per second) | Burst | | ---- | ---- | | 1 | 5 |  The `x-amzn-RateLimit-Limit` response header returns the usage plan rate limits that were applied to the requested operation, when available. The table above indicates the default rate and burst values for this operation. Selling partners whose business demands require higher throughput may see higher rate and burst values than those shown here. For more information, see [Usage Plans and Rate Limits in the Selling Partner API](https://developer-docs.amazon.com/sp-api/docs/usage-plans-and-rate-limits-in-the-sp-api).
     * @param {MessagingApiGetMessagingActionsForOrderRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    getMessagingActionsForOrder(requestParameters: MessagingApiGetMessagingActionsForOrderRequest, options?: any): Promise<import("axios").AxiosResponse<GetMessagingActionsForOrderResponse, any>>;
    /**
     * Sends a message providing the buyer an invoice
     * @param {MessagingApiSendInvoiceRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MessagingApi
     */
    sendInvoice(requestParameters: MessagingApiSendInvoiceRequest, options?: any): Promise<import("axios").AxiosResponse<InvoiceResponse, any>>;
}
